version: "2"

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3

checks:
  method-complexity:
    enabled: true
    config:
      threshold: 40
  argument-count:
    enabled: false
    config:
      threshold: 7
  method-lines:
    enabled: true
    config:
      threshold: 70

exclude_patterns:
  - ".*"
  - "LICENSE"
  - "*.md"
  - "cmaclp/tests/cmaclp_test_model.py"
  - "*.yml"
  - "*.yaml"
