[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel", "python-build", "pytest-cov"]

#[tool.setuptools.package-data]
#"cma.data" = ["*.csv", "*.h5ad"]

[tool.bumpver]
current_version = "0.0.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message  = "Bump version {old_version} -> {new_version}"
commit          = true
tag             = true
push            = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"setup.py" = ["{version}"]

