# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main and develop" branch
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}

    # Docker Hub image that `postgres-job` executes in
    #container: node:latest
    # service containers to run with `postgres-job`
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Check-out repository
      uses: actions/checkout@v2

      #- name: Install Python dependencies
      #  uses: py-actions/py-dependency-install@v4
        
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: bioconda, conda-forge, defaults
        use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
        auto-update-conda: true
        auto-activate-base: true
        
    - name: Install cmaclp pip
      run: |
            echo "begin: PATH=$PATH;"

            conda create -y --name cmaclp pip python=3.9

            conda activate cmaclp || true
            echo "after conda activate cmaclp: PATH=$PATH;"
            which cmaclp || true
            # Use cmaclp in ci-cd workflow
      
    # Builds a wheel needed for the CD part
    - name: Build wheel of package
      run: pip wheel --no-deps -w dist .
      
    - name: Creating needed directories
      run: mkdir -p dist_artifacts data figures
      
    - name: Copying artifact to artifact dir
      run: cp dist/*.whl dist_artifacts/
  
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: wheel artifact
        path: dist_artifacts/*.whl
        
    # Test if the created wheel file can be installed
    - name: Install wheel of package into conda env
      run: pip install dist/*.whl --force-reinstall
      
    # Download data into own directory
    - name: Download labels  
      run: curl -o data/small_training_labels_meta.csv https://zenodo.org/record/8091117/files/small_training_labels_meta.csv?download=1

    - name: Download test
      run: curl -o data/small_test.h5ad https://zenodo.org/record/7970737/files/small_test.h5ad?download=1

    - name: Download training
      run: curl -o data/small_cma_meta_atlas.h5ad https://zenodo.org/record/8091117/files/small_cma_meta_atlas.h5ad?download=1

    - name: Run unit tests
      run: |
        pytest cmaclp/tests/cmaclp_test.py -vvv --disable-pytest-warnings \
        --cov=./ --cov-report=xml

    - name: Upload code coverage ☂️
      uses: paambaati/codeclimate-action@v4.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        
    # Running end-to-end tests CLI functions
    - name: Running end-to-end testing    
      run: pytest cmaclp/tests/cmaclp_test_end_to_end.py --cov

  cd:
    # Only run this job if the "ci" job passes
    needs: ci
    
    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Create dist dir
      run: mkdir -p dist

    - name: Download artifact
      uses: actions/download-artifact@master
      with:
        name: wheel artifact
        path: dist
  
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

# TO DO: write unit tests and add Codecov
  test_model_cornea:
    # Set up operating system
    needs: ci

    runs-on: self-hosted
    
    defaults:
      run:
        shell: bash -l {0}

    # Docker Hub image that `postgres-job` executes in
    #container: node:latest
    # service containers to run with `postgres-job`
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Check-out repository
      uses: actions/checkout@v2

      #- name: Install Python dependencies
      #  uses: py-actions/py-dependency-install@v4
        
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: bioconda, conda-forge, defaults
        use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
        auto-update-conda: true
        auto-activate-base: true

    - name: Install cmaclp pip
      run: |
            echo "begin: PATH=$PATH;"
            conda create -y --name cmaclp pip python=3.9
            conda activate cmaclp || true
            echo "after conda activate cmaclp: PATH=$PATH;"
            which cmaclp || true
            # Use cmaclp in ci-cd workflow

    - name: Create dist dir
      run: mkdir -p dist figures data test_output

    - name: Download artifact
      uses: actions/download-artifact@master
      with:
        name: wheel artifact
        path: dist
        
    # Installs from wheel if ci is finished
    - name: Install wheel of package into conda env
      run: pip install dist/*.whl --force-reinstall

    # Download data into own directory
    - name: Download labels  
      run: curl -o data/training_labels_meta.csv https://zenodo.org/record/8091117/files/training_labels_meta.csv?download=1

    - name: Download CV data
      run: curl -o data/cma_meta_atlas.h5ad https://zenodo.org/record/8091117/files/cma_meta_atlas.h5ad?download=1

    - name: Download ML tracking packages
      run: pip install dagshub mlflow
      
    - name: Install git
      run: conda install git
      
    # Pre-process 
    # Running prediction function
    - name: Running CV and logging results to DagsHub
      env:
        DH_key: ${{ secrets.DH_key }}
      run: python3 cmaclp/tests/cmaclp_test_model.py

